### ISSUE TITLE
Allow specifying "name" at runtime?

### ISSUE THREAD

**Issue by tjko** [Memotech-Bill/bluetooth-stdio#1]
Thanks for making this public. Library looks very nice. 

Would it be possible to allow specifying the (bluetooth service) name at runtime, when initializing the library?

It would be nice to be able to set the "name" at runtime... My use case would be to have generic firmware by default
generate "unique" bluetooth name at runtime, so that multiple devices (with same firmware) would not have same bluetooth name...

Btw, in README.md there seems to be a typo?  ```-DNAME="Pico"``` probably should be ```-DBT_NAME="Pico"``` ?

**Comment by Memotech-Bill** [comment]
I have added an alternative initialisation routine, which allows you to specify the service name:

````
bool stdio_bt_init_name (const char *psName);
````

I have also fixed the typo in the README. Thank you for that.

**Comment by tjko** [comment]
Thanks! Looks great.
